title: "Lone Dissent"
description: "An Exercise in Supreme Obstinacy"
icon: /images/courts/hughes7/hughes7-small.jpg
local: true
footer-links:
  dribbble:
  email: Jeff@pcjs.org
  facebook:
  flickr:
  github: jeffpar/lonedissent
  instagram:
  linkedin:
  pinterest:
  rss: feed.xml
  twitter: jeffpar
  stackoverflow1: users/3357876/jeffpar
  youtube:
  googleplus:

disqus:

analytics_gtag:

url: http://localhost:4000

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - gulpfile.js
  - package*.json
  - /_pages/cases
  - /_pages/justices
  - /lib
  - /node_modules
  - /sources
  - /tmp
