title: "Lone Dissent"
description: "An Exercise in Supreme Obstinacy"
icon: /images/courts/hughes7/hughes7-small.jpg
local: false
footer-links:
  dribbble:
  email: Jeff@pcjs.org
  facebook:
  flickr:
  github: jeffpar/lonedissent
  instagram:
  linkedin:
  pinterest:
  rss: feed.xml
  twitter: jeffpar
  stackoverflow:
  youtube:
  googleplus:

disqus:

analytics_gtag: UA-131809531-1

url: https://lonedissent.org

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - gulpfile.js
  - package*.json
  - /audio
  - /lib
  - /node_modules
  - /sources/justia
  - /sources/loc
  - /sources/oyez/cases
  - /sources/scotus/transcripts
  - /sources/sites
  - /tmp
