source: .
destination: ./docs
title: "Lone Dissent"
description: "An Exercise in Supreme Obstinacy"
icon: /assets/images/courts/hughes7/hughes7-small.jpg
local: false

footer-links:
  dribbble:
  email: loners@pcjs.org
  facebook:
  flickr:
  github: jeffpar/lonedissent
  instagram:
  linkedin:
  pinterest:
  rss: feed.xml
  twitter: jeffpar
  stackoverflow:
  youtube:
  googleplus:

disqus:

analytics_gtag: UA-131809531-1

url: https://lonedissent.org

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - "*.sh"
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - /gulpfile.js
  - /package*.json
  - /.history
  - /audio
  - /briefs
  - /lib
  - /logs
  - /node_modules
  - /sources/freelaw
  - /sources/justia
  - /sources/lba
  - /sources/ld
  - /sources/loc
  - /sources/other/**/*.pdf
  - /sources/oyez/advocates
  - /sources/oyez/cases
  - /sources/oyez/courts
  - /sources/oyez/justices
  - /sources/oyez/justices_by_court
  - /sources/oyez/transcripts
  - /sources/schs
  - /sources/scdb/*.csv
  - /sources/scotus/journals
  - /sources/scotus/lists
  - /sources/scotus/transcripts/arguments
  - /sources/sites
  - /sources/ssrn
  - /tmp
