title: "PCjs Machines"
title: "Lone Dissent"
description: "An Exercise in Supreme Obstinacy"
theme: jekyll-theme-slate
exclude: [/lib", "/node_modules", "/*.js", "/package*.json"]
markdown: kramdown
encoding: utf-8
